[workspace]
members = [
    "01_intro/*",
    "02_basic_calculator/*",
    "03_ticket_v1/*",
    "04_traits/*",
    "05_ticket_v2/*",
    "06_ticket_management/*",
    "07_threads/*"
]
resolver = "2"
